export const labels = {
  loginHeading: 'Manager Login',
  email: 'Email',
  password: 'Password',
  addDriver: 'Add Driver',
  login: 'Login',
  scan: 'Scan',
  jobs: 'Jobs',
  startJob: 'Start Job',
  inventory: 'Inventory',
  clearnce: 'Clearance',
  myJobs: 'My Jobs',
  createJobs: 'Create Jobs',
  assignedTo: 'Assigned To',
  rentalHistory: 'Rental History',
  logout: 'Logout',
  search: 'Search',
  groups: 'Groups',
  assignJob: 'Assign Job',
  view: 'View',
  fullView: 'Full View',
  date: '24th July - 26 July',
  jobTitle: 'Job Title',
  scheduleForm: 'Schedule Form',
  scheduleEnd: 'Schedule End',
  addGroup: 'Add Group',
  group: 'Group',
  itemTitle: 'Item Title',
  selectLatLng: 'Select Lat, Lng from map',
  assignJobTo: 'Assign job to',
  createJob: 'Create Job',
  itemTitle: 'Item Title',
  jobDetails: 'Job Detail',
  map: 'Map',
  supervisor: 'Supervisor',
  supervisorName: 'Supervisor Name',
  edit: 'Edit',
  delete: 'Delete',
  selectEmployee: 'Select Employee',
  selectRole: 'Select Role',
  setClearanceLevel: 'Set Clearance Level',
  sendToMaintaince: 'Send to Maintenance',
  onMaintenance: 'On Maintenance',
  onRent: 'On Rent',
  groupTitle: 'Group Title',
  selectMaintenanceWorker: 'Select Maintenance Worker',
  details: 'Details',
  send: 'Send',
  clearanceLevel: 'Clearance Level',
  manager: 'manager',
  supervisor: 'supervisor',
  maintenanceApp: 'maintenanceApp',
  userApp: 'user',
  driverApp: 'Driver',
  assigningJobs: 'Assigning Jobs',
  assignTo: 'Assign to',
  driverName: 'Driver Name',
  addedDriver: 'Added Driver',
  todoList: 'Todo List',
  scanQRCode: 'Scan QR Code',
  uploadPic: 'Upload Picture',
  done: 'Done',
  current: 'Current',
  past: 'Past',
  maintenance: 'Maintenance',
  itemOfMaintenance: 'Item of Maintenance',
  user: 'UserApp',
  reserve: 'Reserve',
  reserveUntil: 'Reserve Until',
  time: '15:00',
  detailmsg:
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
};
